account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change-username/', views.change_username, name='change_username'),
    path('change-password/', views.change_password, name='change_password'),
    path('change-budget/', views.change_budget, name='change_budget'),
    path('change-email/', views.change_email, name='change_email'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-forgot-password/<str:slug>/<str:token>/', views.forgot_password_reset, name='reset_forgot_password')
]

cashbuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

categories/urls.py
from django.urls import path
from . import views 


app_name = 'categories'

urlpatterns = [
    path('', views.view, name='view'),
    path('create/', views.create_category, name='create'),
    path('delete/<str:slug>/', views.delete_category, name='delete'),
    path('edit/<str:slug>/', views.edit, name='edit'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'account:dashboard' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'categories:create' %}">Add Category</a>
                <a class="nav-link" href="{% url 'transactions:create' %}">Add Transaction</a>
                <a class="nav-link" href="{% url 'categories:view' %}">Categories</a>
                <a class="nav-link" href="{% url 'transactions:view' 'all' %}">Transactions</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'account:change_username' %}">Change Username</a>
                        <a class="dropdown-item" href="{% url 'account:change_password' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'account:change_email' %}">Change Email</a>
                        <a class="dropdown-item" href="{% url 'account:change_budget' %}">Change Budget</a>
                    </div>
                </li>
                {% if user.pk %}
                    <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <svg class="wave" viewBox="0 0 1440 675" preserveAspectRatio="none" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 284.409C130.265 148.842 453.059 -42.9697 702.121 274.317C951.183 591.605 1238.1 283.064 1350.43 89.1324C1381.94 39.5142 1444.58 -42.0614 1442.97 28.5814C1441.36 99.2242 1442.3 491.628 1442.97 679H0V284.409Z" fill="#3A6F00" stroke="#3A6F00"/>
    </svg>    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}
{% block content %}
<div class="dashboard-content">
    <h2 class="name-text">{{ user.username }}'s balance:</h2>
    <h1 class="balance">${{ user.budget }}</h1>
    <div class="bar"></div>
    <div class="transactions">
        <h4>Recent Transactions</h4>
        <hr>
        <table class="table">
            <thead class="table-header">
                <tr>
                  <th scope="col">Category</th>
                  <th scope="col">Price</th>
                  <th scope="col">Date</th>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td scope="row" class="table-category">
                        <div class="td-div">
                            <b>{{ transaction.category }}</b>
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            ${{ transaction.amount }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.date_created }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.title }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.description }}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <a href="{% url 'transactions:view' sort_by='all' %}"><button class="btn">View All Transactions</button></a>
</div>
{% endblock %}

templates/edit_transaction.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create Transaction{% endblock %}
{% block content %}
<form method="post">
    <legend>Edit Transaction</legend>
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Edit</button>
</form>
{% endblock %}

templates/forgot_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <style>
        .email-wrapper {
            position: relative;
            top: 0;
            background: url('https://cash-buddy.herokuapp.com/static/img/email_background.png');
            padding: 50px;
            margin: auto;
            border-radius: 5px;
        }   

        .email-content {
            position: relative;
            background-color: white;
            padding: 30px;
            color: black;
            border-radius: 5px;
            font-family: 'Ubuntu', 'Arial';
        }

        button {
            text-align: center;
            background-color: #79A768;
            height: 40px;
            padding-left: 30px;
            padding-right: 30px;
            border: 0;
            border-radius: 5px;
            color: white;

            transition: background-color 0.2s ease-in;
        }

        button:hover {
            background-color: #3A6F00;
        }

        svg {
            fill: #3A6F00;
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            line-height: 0;
        }

        @media screen and (max-width: 575px) {
            h1 {
                font-size: 1.5rem;
            }

            p {
                font-size: 0.8rem;
            }

            .email-wrapper {
                padding: 20px;
            }

            .email-content {
                padding: 15px;
            }
        }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="email-content">
            <h1>Hello {{ user.username }},</h1>
            <p>Here is your password reset link. Be sure to reset your password within 10 minutes or the link will expire.</p>
            <p>If you didn't sign up for a Cashbuddy account, kindly disregard this email.</p>
            <a href="{{ protocol }}://{{ site_name }}{% url 'account:reset_forgot_password' user.get_slug token %}"><button>Reset Password</button></a>
            <p>- Your buddies</p>
            <p><i>The Cashbuddy Team</i></p>
        </div>
    </div>
</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}
{% block content %}
<form method="post">
    <legend>{{ title }}</legend>
    {% if type == 'transaction' and  user.budget < 0 %}
    <div class="alert alert-warning">
        Warning: you have spent past your budget.
    </div>
    {% endif %}
    {{ form|crispy }}
    {% csrf_token %}
    {% if type == 'register' %}
        <p>Already have an account? Log in <a href="{% url 'account:login' %}">here</a></p>
    {% elif type == 'login' %}
        <p>Don't have an account? Register <a href="{% url 'account:register' %}">here</a></p>
        <p>Forgot your password? Reset <a href="{% url 'account:forgot_password' %}">here</a></p>
    {% endif %}
    <button type="submit" class="btn btn-primary">{{ btn_text }}</button>
</form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}
{% block content %}
<div class="home-content">
    <div class="left-text">
        <h1>Using Notes, or worse... PAPER to track your budget? </h1>
        <p>Worry less about losing your expense records with Cashmate</p>
        <div class="join-btn">
            <a href="{% url 'account:register' %}"><button class="btn">Use Cashbuddy For Free</button></a>
        </div>
    </div>
    <img class="hero-img" src="{% static 'img/hero-img.png' %}" alt="hero-img" />
</div>
{% endblock %}

templates/list_categories.html
{% extends "base.html" %}
{% load static %}
{% block title %}View Categories{% endblock title %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/list_transactions.css' %}"/>
{% endblock %}
{% block content %}
<div class="list-content">
    <table class="table">
        <thead class="table-header">
            <tr>
            <th scope="col">Category Name</th>
            <th></th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            {% for category in page_obj.object_list %}
                <tr>
                    <td>
                        <div class="td-div">
                            {{ category.name }}
                        </div>
                    </td>
                    <td><a href="{% url 'categories:edit' category.get_slug %}"><button class="btn btn-primary">Edit</button></a></td>
                    <td><a href="{% url 'categories:delete' category.get_slug %}"><button class="btn btn-primary">Delete</button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav class="pagination-controls">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="?page=1"><<</a></li>
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.get_previous_page }}">Previous</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
        </ul>
    </nav>
</div>
{% endblock content %}

templates/list_transactions.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}View Categories{% endblock title %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/list_transactions.css' %}"/>
{% endblock %}
{% block content %}
<div class="list-content">
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Change Sort</button>
    </form>
    <table class="table">
        <thead class="table-header">
            <tr>
              <th scope="col">Category</th>
              <th scope="col">Price</th>
              <th scope="col">Date</th>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th></th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in page_obj %}
                <tr>
                    <td scope="row" class="table-category">
                        <div class="td-div">
                            <b>{{ transaction.category }}</b>
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            ${{ transaction.amount }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.date_created }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.title }}
                        </div>
                    </td>
                    <td>
                        <div class="td-div">
                            {{ transaction.description }}
                        </div>
                    </td>
                    <td><a href="{% url 'transactions:edit' transaction.get_slug %}"><button class="btn btn-primary">Edit</button></a></td>
                    <td><a href="{% url 'transactions:delete' transaction.get_slug %}"><button class="btn btn-primary">Delete</button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav class="pagination-controls">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="?page=1"><<</a></li>
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.get_previous_page }}">Previous</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">Next</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
        </ul>
    </nav>
</div>
{% endblock content %}